# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaque_id', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=20)),
                ('home', models.CharField(max_length=20)),
                ('score', models.CharField(max_length=20)),
                ('away', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('leaque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Leaque')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Week'),
        ),
    ]
